/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tesdarah;
import asamurat.java;
import ResikoJantung.java;
import glukosa.java;
import java.text.SimpleDateFormat;
import java.util.Date;
import kolesterol.java;
import tensi.java;
/**
 *
 * @author 0xr00t
 */
public class GUI_TESDarah extends javax.swing.JFrame {

    /**
     * Creates new form GUI_TESDarah
     */
    public GUI_TESDarah() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        umur_user = new javax.swing.JTextField();
        gol_user = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        islaki_user = new javax.swing.JRadioButton();
        isperempuan_user = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        diastol_user = new javax.swing.JTextField();
        sistol_user = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        asamur_user = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        gula_user = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        isPuasa_user = new javax.swing.JCheckBox();
        hdl_user = new javax.swing.JTextField();
        ldl_user = new javax.swing.JTextField();
        kol_tot = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        hasil_user = new javax.swing.JLabel();
        total_kol_user1 = new javax.swing.JLabel();
        tanggalMCU = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tes Darah");

        jLabel1.setText("Tanggal MCU");

        jLabel2.setText("Nama");

        nama_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_userActionPerformed(evt);
            }
        });

        jLabel3.setText("Umur");

        umur_user.setMinimumSize(new java.awt.Dimension(80, 22));
        umur_user.setPreferredSize(new java.awt.Dimension(80, 22));

        gol_user.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));

        jLabel4.setText("Golongan darah");

        jLabel5.setText("Jenis Kelamin");

        islaki_user.setText("Laki laki");
        islaki_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                islaki_userActionPerformed(evt);
            }
        });

        isperempuan_user.setText("Perempuan");

        jLabel6.setText("Tensi");

        jLabel7.setText("sistol");

        jLabel8.setText("diastol");

        diastol_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diastol_userActionPerformed(evt);
            }
        });

        jLabel9.setText("Nilai Asam Urat");

        asamur_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asamur_userActionPerformed(evt);
            }
        });

        jLabel10.setText("Glukosa");

        gula_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gula_userActionPerformed(evt);
            }
        });

        jLabel11.setText("HDL");

        jLabel12.setText("LDL");

        isPuasa_user.setText("Puasa");
        isPuasa_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isPuasa_userActionPerformed(evt);
            }
        });

        hdl_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hdl_userActionPerformed(evt);
            }
        });

        ldl_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldl_userActionPerformed(evt);
            }
        });

        kol_tot.setText("Kolesterol Total: ");

        jButton1.setText("Hasil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        hasil_user.setText("kriterria hasil");

        total_kol_user1.setText("....");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(asamur_user, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                            .addComponent(gula_user)
                                            .addComponent(hdl_user)
                                            .addComponent(ldl_user)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(kol_tot))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addComponent(hasil_user))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(total_kol_user1))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(37, 37, 37)
                                .addComponent(islaki_user)
                                .addGap(43, 43, 43)
                                .addComponent(isperempuan_user))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gol_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama_user, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(umur_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tanggalMCU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(505, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diastol_user, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sistol_user, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(519, 519, 519))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(isPuasa_user)
                .addGap(339, 339, 339))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(tanggalMCU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(isPuasa_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nama_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(umur_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gol_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(islaki_user)
                    .addComponent(isperempuan_user))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diastol_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sistol_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asamur_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gula_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hdl_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ldl_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kol_tot)
                    .addComponent(total_kol_user1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(hasil_user))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nama_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_userActionPerformed

    private void islaki_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_islaki_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_islaki_userActionPerformed

    private void asamur_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asamur_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asamur_userActionPerformed

    private void gula_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gula_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gula_userActionPerformed

    private void isPuasa_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isPuasa_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isPuasa_userActionPerformed

    private void hdl_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hdl_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hdl_userActionPerformed

    private void ldl_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldl_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ldl_userActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // asamur v
        // glukosa v
        // tensi v
        // kolesterol v
        // resikojantung v
        String nama = nama_user.getText();
        int umur = Integer.parseInt(umur_user.getText());
        String GolDar = gol_user.getSelectedItem().toString();
       
        
        boolean isLaki = islaki_user.isSelected();
        boolean isPuasa = isPuasa_user.isSelected();
        
        /*if (islaki_user.isSelected()) {
        String laki = islaki_user.getText();
        } else if (isperempuan_user.isSelected()) {
        String perempuan = isperempuan_user.getText();
        }*/
        
        Date tanggalDipilih = tanggalMCU.getDate();
         // Define the desired date format
        // Common formats:
        // "yyyy-MM-dd" -> 2025-05-24 (Good for databases, international standard)
        // "dd-MM-yyyy" -> 24-05-2025 (Common in many regions)
        // "dd/MM/yyyy" -> 24/05/2025
        // "MM/dd/yyyy" -> 05/24/2025 (Common in the US)
        // "EEEE, dd MMMM yyyy" -> Sabtu, 24 Mei 2025 (Full day name, month name in Indonesian - if locale is set)

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Choose your preferred format
        String dateString = sdf.format(tanggalDipilih);
        
        
        int diastol = Integer.parseInt(diastol_user.getText());
        int sistol = Integer.parseInt(sistol_user.getText());
                
        float nilai_asam_urat = Float.parseFloat(asamur_user.getText());
        int  nilai_glukosa = Integer.parseInt(gula_user.getText());
        int HDL_user = Integer.parseInt(hdl_user.getText());
        int LDL_user = Integer.parseInt(ldl_user.getText());
        
        
        asamurat dataAsamUrat = new asamurat(nilai_asam_urat, umur);
        String hasilAsamUrat = dataAsamUrat.kriteria();
       // hasil_user.setText(hasilAsamUrat);
        
        glukosa dataGlukosa = new glukosa(GolDar, isLaki, nilai_glukosa, isPuasa);
        String hasilGlukosa = dataGlukosa.kriteria();
       // hasil_user.setText(hasilGlukosa);
        
        tensi dataTensi = new tensi(sistol, diastol);
        String hasilTensi = dataTensi.kriteria();
        
        ResikoJantung dataResikoJantung = new ResikoJantung(GolDar, isLaki, HDL_user, LDL_user);
        String hasilResikoJantung = dataResikoJantung.kriteria();
        
        kolesterol dataKolesterol = new kolesterol(GolDar, isLaki, HDL_user, LDL_user);
        String hasilKolesterol = dataKolesterol.kriteria();
                
        String combinedHasil = hasilAsamUrat + " " + hasilGlukosa + " " + hasilTensi + " " + hasilResikoJantung + " " + hasilKolesterol;
        
        hasil_user.setText(combinedHasil);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void diastol_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diastol_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diastol_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_TESDarah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_TESDarah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_TESDarah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_TESDarah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_TESDarah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asamur_user;
    private javax.swing.JTextField diastol_user;
    private javax.swing.JComboBox<String> gol_user;
    private javax.swing.JTextField gula_user;
    private javax.swing.JLabel hasil_user;
    private javax.swing.JTextField hdl_user;
    private javax.swing.JCheckBox isPuasa_user;
    private javax.swing.JRadioButton islaki_user;
    private javax.swing.JRadioButton isperempuan_user;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel kol_tot;
    private javax.swing.JTextField ldl_user;
    private javax.swing.JTextField nama_user;
    private javax.swing.JTextField sistol_user;
    private com.toedter.calendar.JDateChooser tanggalMCU;
    private javax.swing.JLabel total_kol_user1;
    private javax.swing.JTextField umur_user;
    // End of variables declaration//GEN-END:variables
}
