/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tesdarah;

import javax.swing.JOptionPane;

/**
 *
 * @author 0xr00t
 */
public class TesDar extends javax.swing.JFrame {
    
   
    /**
     * Creates new form TesDar
     */
    public TesDar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        GolDar = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        JK_L = new javax.swing.JRadioButton();
        JK_P = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NilaiAsamUr = new javax.swing.JTextField();
        NilaiUmur = new javax.swing.JTextField();
        GetKriteria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Golongan Darah");

        GolDar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "O", "AB" }));

        jLabel2.setText("Jenis Kelamin");

        JK_L.setText("L");
        JK_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JK_LActionPerformed(evt);
            }
        });

        JK_P.setText("P");
        JK_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JK_PActionPerformed(evt);
            }
        });

        jLabel3.setText("Nilai Umur");

        jLabel4.setText("Nilai asamur");

        NilaiAsamUr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NilaiAsamUrActionPerformed(evt);
            }
        });

        NilaiUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NilaiUmurActionPerformed(evt);
            }
        });

        GetKriteria.setText("Kriteria");
        GetKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetKriteriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(GetKriteria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NilaiUmur, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(NilaiAsamUr)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GolDar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JK_L)
                                .addGap(22, 22, 22)
                                .addComponent(JK_P)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(GolDar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JK_L)
                    .addComponent(JK_P))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NilaiUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NilaiAsamUr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(GetKriteria)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JK_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JK_LActionPerformed
        
    }//GEN-LAST:event_JK_LActionPerformed

    private void JK_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JK_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JK_PActionPerformed

    private void NilaiAsamUrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NilaiAsamUrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NilaiAsamUrActionPerformed

    private void NilaiUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NilaiUmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NilaiUmurActionPerformed

    private void GetKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetKriteriaActionPerformed
        // TODO add your handling code here:
       if (NilaiAsamUr.getText().isEmpty() || NilaiUmur.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Semua field harus diisi!", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if (!JK_L.isSelected() && !JK_P.isSelected()) {
        JOptionPane.showMessageDialog(this, 
            "Pilih jenis kelamin!", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        float nilai = Float.parseFloat(NilaiAsamUr.getText());
        boolean isLaki = JK_L.isSelected();
        String golonganDarah = GolDar.getSelectedItem().toString();
        int umur = Integer.parseInt(NilaiUmur.getText());
        
        asamurat asam = new asamurat();
        asam.setGol(golonganDarah);
        asam.setJK(isLaki);
        asam.setU(umur);
        asam.setN(nilai);
        
        String result = evaluateResult(asam);

        // Show result dialog
        JOptionPane.showMessageDialog(this, 
            "Hasil: " + result, 
            "Kriteria", 
            JOptionPane.INFORMATION_MESSAGE);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Nilai asam urat dan umur harus berupa angka!", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_GetKriteriaActionPerformed
}
   private String evaluateResult(asamurat asam) {
    String result = "";
    boolean isLaki = asam.getJK();
    float nilaiAsam = asam.getN();
    int umur = asam.getU();
    
    if (isLaki) {
        if (umur >= 10 && umur <= 18) {
            if (nilaiAsam <= 5.5 && nilaiAsam >= 3.6) {
                result = "Normal";
            } else {
                result = "SG NORMAL BROO";
            }
        } else if (umur >= 19 && umur <= 40) {
            if (nilaiAsam <= 7.5 && nilaiAsam >= 2) {
                result = "Normal";
            } else {
                result = "SG VROOO";
            }
        } else if (umur > 40) {
            if (nilaiAsam >= 2 && nilaiAsam <= 8.5) {
                result = "Normal";
            } else {
                result = "SG VROOO";
            }
        }
    } else {
        if (umur >= 19 && umur <= 40) {
            if (nilaiAsam <= 6.5 && nilaiAsam >= 2) {
                result = "Normal";
            } else {
                result = "SG NORMAL BROO";
            }
        } else if (umur > 40) {
            if (nilaiAsam <= 8 && nilaiAsam >= 2) {
                result = "Normal";
            } else {
                result = "SG VROOO";
            }
        } else if (umur >= 10 && umur <= 18) {
            if (nilaiAsam >= 3.6 && nilaiAsam <= 4) {
                result = "Normal";
            } else {
                result = "SG VROOO";
            }
        }
    }
    
    // If no condition was met, return this default message
    if (result.isEmpty()) {
        result = "Kriteria tidak diketahui";
    }
    
    return result;
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesDar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesDar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesDar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesDar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesDar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetKriteria;
    private javax.swing.JComboBox<String> GolDar;
    private javax.swing.JRadioButton JK_L;
    private javax.swing.JRadioButton JK_P;
    private javax.swing.JTextField NilaiAsamUr;
    private javax.swing.JTextField NilaiUmur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

   
}
