/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas1;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author 0xr00t
 */
public class aplikasi_GUI extends javax.swing.JFrame {


    int nomorUrut = 0;
    private DefaultTableModel tableModel;
    
    public aplikasi_GUI() {
        initComponents();
         setTitle("Aplikasi Data Pendaftar - PBO 2025");
         tableModel = (DefaultTableModel) tableData.getModel();
         
        String[] kolom = {"Nama", "NIM", "Sikap", "Tugas", "UTS", "UAS", "Rerata", "Huruf"};
        tableModel.setColumnIdentifiers(kolom);
        tableModel.setRowCount(0);
        
        tambahDataAwal();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nama_USER = new javax.swing.JTextField();
        NIM_USER = new javax.swing.JTextField();
        NS_USER = new javax.swing.JTextField();
        NT_USER = new javax.swing.JTextField();
        NUTS_USER = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NUAS_USER = new javax.swing.JTextField();
        Reset_form = new javax.swing.JButton();
        Tambah_Data = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Nama");

        jLabel4.setText("NIM");

        jLabel5.setText("Nilai Sikap");

        NIM_USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIM_USERActionPerformed(evt);
            }
        });

        jLabel6.setText("Nilai UTS");

        jLabel7.setText("Nilai Tugas");

        jLabel8.setText("Nilai UAS");

        Reset_form.setText("Reset Form");
        Reset_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_formActionPerformed(evt);
            }
        });

        Tambah_Data.setText("Tambah Data");
        Tambah_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambah_DataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NUTS_USER, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NT_USER, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NUAS_USER, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NS_USER, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NIM_USER, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nama_USER, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Reset_form)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Tambah_Data))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Nama_USER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NIM_USER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NS_USER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NT_USER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUTS_USER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(NUAS_USER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reset_form)
                    .addComponent(Tambah_Data))
                .addContainerGap())
        );

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "NIM", "Nilai Sikap", "Nilai Tugas", "Nilai UTS", "Nilai UAS", "rerata", "Skala"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableData.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableData);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tambahDataKeTabel() {
        try {
            // 1. Ambil data dari text field
            Pendaftar temp = new Pendaftar();
            
            temp.setNama(Nama_USER.getText());
            temp.setNim(NIM_USER.getText());
            // Validasi input tidak boleh kosong
            if (temp.getNama().isEmpty() || temp.getNim().isEmpty() || NS_USER.getText().isEmpty() ||
                NT_USER.getText().isEmpty() || NUTS_USER.getText().isEmpty() || NUAS_USER.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 2. Konversi nilai ke double (dengan validasi)
            /*
            double sikap = Double.parseDouble(NS_USER.getText());
            double tugas = Double.parseDouble(NT_USER.getText());
            double uts = Double.parseDouble(NUTS_USER.getText());
            double uas = Double.parseDouble(NUAS_USER.getText());
            */
            temp.setSikap(Float.parseFloat(NS_USER.getText()));
            temp.setTugas(Float.parseFloat(NT_USER.getText()));
            temp.setUts(Float.parseFloat(NUTS_USER.getText()));
            temp.setUas(Float.parseFloat(NUAS_USER.getText())) ;
            
            String nama = Nama_USER.getText();
            String nim = NIM_USER.getText();
            float sikap = temp.getSikap();
            float tugas = temp.getTugas();
            float uts = temp.getUts();
            float uas = temp.getUas();
            
            
            // 3. Buat objek Pendaftar (logika perhitungan otomatis berjalan di constructor)
            // Pastikan Anda memiliki kelas Pendaftar.java di package uas1
            Pendaftar pendaftar = new Pendaftar(nama, nim, sikap, tugas, uts, uas);

            // 4. Tambahkan data ke tabel
            tableModel.addRow(new Object[]{
              //  nomorUrut++,
                pendaftar.getNama(),
                pendaftar.getNim(),
                String.format("%.2f", pendaftar.getSikap()),
                String.format("%.2f", pendaftar.getTugas()),
                String.format("%.2f", pendaftar.getUts()),
                String.format("%.2f", pendaftar.getUas()),
                String.format("%.2f", pendaftar.getRerata()), // Format desimal
                pendaftar.getHuruf()
            });

            // 5. Kosongkan form setelah data berhasil ditambahkan
            resetForm();

        } catch (NumberFormatException ex) {
            // Tangani jika input nilai bukan angka
            JOptionPane.showMessageDialog(this, "Input nilai harus berupa angka!", "Error Format Angka", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Mengosongkan semua field input pada form.
     */
    private void resetForm() {
        Nama_USER.setText("");
        NIM_USER.setText("");
        NS_USER.setText("");
        NT_USER.setText("");
        NUTS_USER.setText("");
        NUAS_USER.setText("");
        Nama_USER.requestFocus(); // Fokuskan kursor ke field nama
    }
    
    private void tambahDataAwal() {
        // Pastikan Anda memiliki kelas Pendaftar.java di package uas1
        List<Pendaftar> dataAwal = new ArrayList<>();
        dataAwal.add(new Pendaftar("Budi Santoso", "24001", 90, 88, 85, 92));
        dataAwal.add(new Pendaftar("Citra Lestari", "24002", 82, 80, 78, 85));
        dataAwal.add(new Pendaftar("Doni Firmansyah", "24003", 75, 72, 68, 70));
        dataAwal.add(new Pendaftar("Eka Putri", "24004", 60, 65, 55, 62));
        dataAwal.add(new Pendaftar("Fajar Nugroho", "24005", 50, 45, 30, 55));

        for (Pendaftar p : dataAwal) {
            tableModel.addRow(new Object[]{
             //   nomorUrut++,
                p.getNama(),
                p.getNim(),
                String.format("%.2f", p.getSikap()),
                String.format("%.2f", p.getTugas()),
                String.format("%.2f", p.getUts()),
                String.format("%.2f", p.getUas()),
                String.format("%.2f", p.getRerata()),
                p.getHuruf()
            });
        }
    }
    
    
    private void Reset_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_formActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_Reset_formActionPerformed

    
    
    private void NIM_USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIM_USERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIM_USERActionPerformed

    private void Tambah_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambah_DataActionPerformed
           // TODO add your handling code here:
           tambahDataKeTabel();
           
    }//GEN-LAST:event_Tambah_DataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplikasi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplikasi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplikasi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplikasi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplikasi_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIM_USER;
    private javax.swing.JTextField NS_USER;
    private javax.swing.JTextField NT_USER;
    private javax.swing.JTextField NUAS_USER;
    private javax.swing.JTextField NUTS_USER;
    private javax.swing.JTextField Nama_USER;
    private javax.swing.JButton Reset_form;
    private javax.swing.JButton Tambah_Data;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableData;
    // End of variables declaration//GEN-END:variables
}
