
package pbo_uas;


import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 0xr00t
 */
public class GUI_petani extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    // List untuk menyimpan objek petani (berfungsi sebagai database sementara)
    private final List<petani> daftarPanen = new ArrayList<>();
    // Formatter untuk mengubah angka menjadi format mata uang Rupiah
     private final NumberFormat formatter = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
    
    
    
    public GUI_petani() {
        initComponents();
       
        setTitle("aplikasi petani");
        tableModel = (DefaultTableModel) tablePanen.getModel();
        inisialisasiTabel();
        
        // Memuat data awal untuk demonstrasi
        muatDataAwal();
        
        programUtama.main(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hapus = new javax.swing.JButton();
        Tambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nama_USER = new javax.swing.JTextField();
        pend_bruto = new javax.swing.JTextField();
        biaya_pupuk = new javax.swing.JTextField();
        tenagaKerja = new javax.swing.JTextField();
        sewa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panen_ke_USER = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePanen = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        Tambah.setText("Tambah");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        jLabel3.setText("biaya_pupuk");

        jLabel4.setText("sewa");

        jLabel5.setText("tenaga kerja");

        pend_bruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pend_brutoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama");

        jLabel2.setText("pend_bruto");

        panen_ke_USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panen_ke_USERActionPerformed(evt);
            }
        });

        jLabel6.setText("panen_ke");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nama_USER, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(panen_ke_USER)
                    .addComponent(pend_bruto)
                    .addComponent(biaya_pupuk)
                    .addComponent(tenagaKerja)
                    .addComponent(sewa))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nama_USER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panen_ke_USER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pend_bruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(biaya_pupuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tenagaKerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        tablePanen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "nama", "panen ke", "pend_bruto", "biaya_pupuk", "tenaga kerja", "pend_net", "owner_bruto", "owner_net", "penyakap_bruto", "penyakap_net", "sewa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePanen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePanenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePanen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tambah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1358, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hapus)
                    .addComponent(Tambah))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePanenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePanenMouseClicked
       int barisTerpilih = tablePanen.getSelectedRow();
        
        if (barisTerpilih != -1) {
            
            petani p = daftarPanen.get(barisTerpilih);
            
            // Mengisi form dengan data dari objek petani
            Nama_USER.setText(p.getNama());
            panen_ke_USER.setText(String.valueOf(p.getPanen_ke()));
            // Mengubah nilai double ke String untuk ditampilkan di text field
            pend_bruto.setText(String.valueOf(p.getPend_bruto()));
            biaya_pupuk.setText(String.valueOf(p.getBiaya_pupukpestisida()));
            tenagaKerja.setText(String.valueOf(p.getTenagakerja()));
            sewa.setText(String.valueOf(p.getSewa()));
        }
    }//GEN-LAST:event_tablePanenMouseClicked

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        try {
            // Ambil data dari form
            
            
            String nama = Nama_USER.getText();
            String sPendBruto = pend_bruto.getText();
            String sBiayaPupuk = biaya_pupuk.getText();
            String sTenagaKerja = tenagaKerja.getText();
            String sSewa = sewa.getText();
            int panenKe = Integer.parseInt(panen_ke_USER.getText());
            

            // Validasi input tidak boleh kosong
            if (nama.isEmpty() || sPendBruto.isEmpty() || sBiayaPupuk.isEmpty() || sTenagaKerja.isEmpty() || sSewa.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Konversi nilai ke tipe data double
            double dPendBruto = Double.parseDouble(sPendBruto);
            double dBiayaPupuk = Double.parseDouble(sBiayaPupuk);
            double dTenagaKerja = Double.parseDouble(sTenagaKerja);
            double dSewa = Double.parseDouble(sSewa);
/*
            // Otomatisasi penentuan "Panen Ke-"
            int panenKe = 1;
            for (petani p : daftarPanen) {
                if (p.getNama().equalsIgnoreCase(nama)) {
                    panenKe++;
                }
            }
*/          
            /*
            for (petani p : daftarPanen) {
                if (p.getNama().equalsIgnoreCase(nama)) {
                    panenKe++;
                }
            }*/

            //Buat objek petani baru
            petani petaniBaru = new petani(nama, panenKe, dPendBruto, dBiayaPupuk, dTenagaKerja, dSewa);

            //Tambahkan ke list dan refresh tabel
            daftarPanen.add(petaniBaru);
            refreshTabel();
            resetForm();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input untuk angka harus valid!", "Error Format Angka", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_TambahActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        int barisTerpilih = tablePanen.getSelectedRow();
        
        // Cek apakah ada baris yang dipilih
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Konfirmasi penghapusan
        int pilihan = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        
        if (pilihan == JOptionPane.YES_OPTION) {
            // Hapus data dari list
            daftarPanen.remove(barisTerpilih);
            
            // Refresh tabel dan reset form
            refreshTabel();
            resetForm();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        }
    }//GEN-LAST:event_HapusActionPerformed

    private void pend_brutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pend_brutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pend_brutoActionPerformed

    private void panen_ke_USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panen_ke_USERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panen_ke_USERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_petani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_petani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_petani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_petani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_petani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JTextField Nama_USER;
    private javax.swing.JButton Tambah;
    private javax.swing.JTextField biaya_pupuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField panen_ke_USER;
    private javax.swing.JTextField pend_bruto;
    private javax.swing.JTextField sewa;
    private javax.swing.JTable tablePanen;
    private javax.swing.JTextField tenagaKerja;
    // End of variables declaration//GEN-END:variables

    private void inisialisasiTabel() {
        
        String[] kolom = {
            "Nama", "Panen Ke", "Pend. Bruto", "Biaya Pupuk", "Tenaga Kerja",
            "Sewa", "Pend. Net", "Owner Bruto", "Owner Net", "Penggarap Bruto", "Penggarap Net"
        };
        tableModel.setColumnIdentifiers(kolom); 

    // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void muatDataAwal() {
        daftarPanen.add(new petani("Budi", 1, 15000000, 750000, 1500000, 3000000));
        daftarPanen.add(new petani("Joko", 1, 25000000, 1200000, 2000000, 4000000));
        daftarPanen.add(new petani("Budi", 2, 17500000, 800000, 1600000, 3000000));
        
        // Merefresh tampilan tabel
        refreshTabel();
    }

    private void refreshTabel() {
        
        tableModel.setRowCount(0); // Menghapus semua baris yang ada
        
        // Mengisi tabel baris per baris dari list daftarPanen
        for (petani p : daftarPanen) {
            tableModel.addRow(new Object[]{
                p.getNama(),
                p.getPanen_ke(),
                formatter.format(p.getPend_bruto()),
                formatter.format(p.getBiaya_pupukpestisida()),
                formatter.format(p.getTenagakerja()),
                formatter.format(p.getSewa()),
                formatter.format(p.getPend_net()),
                formatter.format(p.getOwner_bruto()),
                formatter.format(p.getOwner_net()),
                formatter.format(p.getPenyakap_bruto()),
                formatter.format(p.getPenyakap_net())
            });
        }
        
    }
    
    private void resetForm() {
        Nama_USER.setText("");
        pend_bruto.setText("");
        biaya_pupuk.setText("");
        tenagaKerja.setText("");
        sewa.setText("");
        panen_ke_USER.setText("");
        
        tablePanen.clearSelection(); // Menghapus seleksi pada tabel
        Nama_USER.requestFocus(); // Mengembalikan fokus ke field Nama
    }
}
