
package uas2;

import java.text.NumberFormat;
import java.time.Month;
import java.time.format.TextStyle;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 0xr00t
 */
public class aplikasi_GUI extends javax.swing.JFrame {

    /**
     * Creates new form aplikasi_GUI
     */
    private DefaultTableModel tableModel;
    
    public aplikasi_GUI() {
        
        initComponents();
        
        initializeTable();
        setTitle("Kalkulator Pendapatan Restoran");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Hasil = new javax.swing.JLabel();
        Hasilpm = new javax.swing.JLabel();
        hasilCs = new javax.swing.JLabel();
        Nama_Restoran = new javax.swing.JTextField();
        HasilBruto = new javax.swing.JTextField();
        HasilListrikAir = new javax.swing.JTextField();
        HasilBahanBaku = new javax.swing.JTextField();
        HasilNet = new javax.swing.JTextField();
        HasilManager = new javax.swing.JTextField();
        HasilSewa = new javax.swing.JTextField();
        HasilPemilik = new javax.swing.JTextField();
        HasilCSR = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Bulan_Laporan = new com.toedter.calendar.JMonthChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Restoran");

        jLabel2.setText("Bulan Laporan");

        jLabel3.setText("Pend. Bruto");

        jLabel4.setText("Peng Listrik/Air");

        jLabel5.setText("Peng Bahan Baku");

        jLabel6.setText("Pendapatan Net: ");

        jLabel7.setText("Manajer (30%):");

        Hasil.setText("Sewa (30%):");

        Hasilpm.setText("Pemilik (30%):");

        hasilCs.setText("CSR (10%):");

        Nama_Restoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_RestoranActionPerformed(evt);
            }
        });

        HasilBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilBrutoActionPerformed(evt);
            }
        });

        HasilListrikAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilListrikAirActionPerformed(evt);
            }
        });

        HasilBahanBaku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilBahanBakuActionPerformed(evt);
            }
        });

        HasilNet.setEditable(false);
        HasilNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilNetActionPerformed(evt);
            }
        });

        HasilManager.setEditable(false);
        HasilManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilManagerActionPerformed(evt);
            }
        });

        HasilSewa.setEditable(false);
        HasilSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilSewaActionPerformed(evt);
            }
        });

        HasilPemilik.setEditable(false);
        HasilPemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilPemilikActionPerformed(evt);
            }
        });

        HasilCSR.setEditable(false);
        HasilCSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilCSRActionPerformed(evt);
            }
        });

        jButton1.setText("Reset Form");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hitung Dan Tambahkan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hasilpm, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasilCs, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nama_Restoran, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(HasilPemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HasilBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(HasilListrikAir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(HasilBahanBaku, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(HasilNet, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(HasilManager, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(HasilSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Bulan_Laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(HasilCSR, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nama_Restoran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Bulan_Laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(HasilBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(HasilListrikAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(HasilBahanBaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(HasilNet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(HasilManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hasil)
                    .addComponent(HasilSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hasilpm)
                    .addComponent(HasilPemilik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasilCs)
                    .addComponent(HasilCSR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Restoran", "Bulan", "Bruto", "Listrik/Air", "Bahan Baku", "Net", "Manager", "Sewa", "Pemilik", "CSR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nama_RestoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_RestoranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama_RestoranActionPerformed

    private void initializeTable() {
        // Mendefinisikan kolom untuk tabel
        String[] columnNames = {
            "Restoran", "Bulan", "Bruto", "Listrik/Air", "Bahan Baku", 
            "Net", "Manager", "Sewa", "Pemilik", "CSR"
        };
        // Membuat table model yang dinamis (bisa ditambah/hapus baris)
        tableModel = new DefaultTableModel(columnNames, 0);
        jTable1.setModel(tableModel);
    }
    
    private void HasilBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilBrutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilBrutoActionPerformed

    private void HasilListrikAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilListrikAirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilListrikAirActionPerformed

    private void HasilBahanBakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilBahanBakuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilBahanBakuActionPerformed

    private void HasilNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilNetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilNetActionPerformed

    private void HasilManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilManagerActionPerformed

    private void HasilSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilSewaActionPerformed

    private void HasilPemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilPemilikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilPemilikActionPerformed

    private void HasilCSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilCSRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilCSRActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Ambil data dari input field
            Restaurant restau_temp = new Restaurant();
            restau_temp.setNama(Nama_Restoran.getText());
            
            int bulanDipilih = Bulan_Laporan.getMonth() + 1;
            Month monthEnum = Month.of(bulanDipilih);
            //String bulan = monthEnum.getDisplayName(TextStyle.FULL, new Locale("id", "ID"));      
            restau_temp.setBulan(monthEnum.getDisplayName(TextStyle.FULL, new Locale("id", "ID")));
            
            
            
            // Konversi input string ke double
            restau_temp.setPendBruto(Double.parseDouble(HasilBruto.getText()));
            restau_temp.setPengListAir(Double.parseDouble(HasilListrikAir.getText()));
            restau_temp.setPengBahan(Double.parseDouble(HasilBahanBaku.getText()));

            
            
            String nama = restau_temp.getNama();
            String bulan = restau_temp.getBulan();
            double bruto = restau_temp.getPendBruto();
            double listrikAir = restau_temp.getPengListAir();
            double bahanBaku = restau_temp.getPengBahan();
            
            if (nama.trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Nama Restoran dan Bulan tidak boleh kosong!", "Error Input", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // 2. Buat objek Restaurant
            Restaurant resto = new Restaurant(nama, bulan, bruto, listrikAir, bahanBaku);

            // 3. Lakukan perhitungan dan tampilkan di form
            // Siapkan format mata uang Rupiah
            NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
            
            HasilNet.setText(currencyFormat.format(resto.getPendNet()));
            HasilManager.setText(currencyFormat.format(resto.getManager()));
            HasilSewa.setText(currencyFormat.format(resto.getSewa()));
            HasilPemilik.setText(currencyFormat.format(resto.getOwner()));
            HasilCSR.setText(currencyFormat.format(resto.getCsr()));

            // 4. Tambahkan data ke tabel
            tableModel.addRow(new Object[]{
                resto.getNama(),
                resto.getBulan(),
                currencyFormat.format(resto.getPendBruto()),
                currencyFormat.format(resto.getPengListAir()),
                currencyFormat.format(resto.getPengBahan()),
                currencyFormat.format(resto.getPendNet()),
                currencyFormat.format(resto.getManager()),
                currencyFormat.format(resto.getSewa()),
                currencyFormat.format(resto.getOwner()),
                currencyFormat.format(resto.getCsr())
            });
        
        programUtama.main(null);
            
        } catch (NumberFormatException e) {
            // Tampilkan pesan error jika input angka tidak valid
            JOptionPane.showMessageDialog(this, "Input Pendapatan dan Pengeluaran harus berupa angka.", "Error Input", JOptionPane.ERROR_MESSAGE);
        }
    
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Nama_Restoran.setText("");
        //Bulan_Laporan.setText("");
        HasilBruto.setText("");
        HasilListrikAir.setText("");
        HasilBahanBaku.setText("");
        
        // Mengosongkan semua field hasil
        HasilNet.setText("");
        HasilManager.setText("");
        Hasil.setText("");
        Hasilpm.setText("");
        hasilCs.setText("");
        
        // Fokuskan kursor ke field pertama
        Nama_Restoran.requestFocus();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplikasi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplikasi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplikasi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplikasi_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplikasi_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JMonthChooser Bulan_Laporan;
    private javax.swing.JLabel Hasil;
    private javax.swing.JTextField HasilBahanBaku;
    private javax.swing.JTextField HasilBruto;
    private javax.swing.JTextField HasilCSR;
    private javax.swing.JTextField HasilListrikAir;
    private javax.swing.JTextField HasilManager;
    private javax.swing.JTextField HasilNet;
    private javax.swing.JTextField HasilPemilik;
    private javax.swing.JTextField HasilSewa;
    private javax.swing.JLabel Hasilpm;
    private javax.swing.JTextField Nama_Restoran;
    private javax.swing.JLabel hasilCs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
